name: Java CI with Gradle

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew build

        - name: Configure credentials
          run: |
            mkdir -p ~/.gradle
            echo "publishing {
              repositories {
                maven {
                  name = 'GitHubPackages'
                  url = uri(\"https://maven.pkg.github.com/${{ github.repository }}\")
                  credentials {
                    username = '${{ github.actor }}'
                    password = '${{ secrets.GITHUB_TOKEN }}'
                  }
                }
              }
            }" >> ~/.gradle/init.gradle

        - name: Publish to GitHub Packages
          run: ./gradlew publish
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_REPOSITORY: ${{ github.repository }}
            GITHUB_ACTOR: ${{ github.actor }}