name: Java CI with Gradle

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew build

        - name: Run tests
          run: ./gradlew test

        - name: Criar config Gradle para GitHub Packages
          run: |
            mkdir -p ~/.gradle
            echo "publishing {
              repositories {
                maven {
                  name = 'GitHubPackages'
                  url = uri('https://maven.pkg.github.com/${{ github.repository }}')
                  credentials {
                    username = '${{ github.actor }}'
                    password = '${{ secrets.GITHUB_TOKEN }}'
                  }
                }
              }
            }" >> ~/.gradle/init.gradle

        - name: Publicar no GitHub Packages
          run: ./gradlew publish
          

        # - name: Publish to GitHub Packages
        #   run: ./gradlew publish
        #   env:
        #     ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
        #     ORG_GRADLE_PROJECT_githubToken: ${{ secrets.GITHUB_TOKEN }}

        # - name: Debug GitHub Packages Publication
        #   run: |
        #     echo "Checking Gradle configuration:"
        #     cat ~/.gradle/gradle.properties || echo "No gradle.properties found"
        #     echo "Listing build/libs directory:"
        #     ls -l build/libs || echo "No build/libs directory found"
        #     echo "Checking environment variables:"
        #     env | grep 'GITHUB\|GRADLE'
        #     echo "Gradle publish dry run:"
        #     ./gradlew publish --dry-run